name: flutter_key_store_cryptography
description: The keystore management and signing package
version: 1.0.0
homepage: http://www.maheshhaldar.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    androidPackage: com.plugin.flutter.cryptography.key_store
    pluginClass: CipherPlugin
