name: flutter_key_store_cryptography
description: This plugin helps you by generating the assymetric RSA key pair, using which you can use encrypt and verify. The keys are generated and persisted in android/ios keystore.
version: 1.0.1
homepage: https://github.com/haldarmahesh/flutter_key_store_cryptography

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    androidPackage: com.plugin.flutter.cryptography.key_store
    pluginClass: CipherPlugin
